name: PR Deploy

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Build Site for PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Patch docusaurus.config.js for PR builds
        run: |
          sed -E -i "s^(baseUrl: .?)'/'^\1'/@${PR_SOURCE_BRANCH}/'^g" docusaurus.config.js
          sed -E -i "s^title: 'Build resilient apps with SAP BTP',^title: 'Build resilient apps with SAP BTP (PR: #${PR_NUMBER})',^g" docusaurus.config.js
          sed -E -i "s^logo: \{^logo: \{href: 'https://github.com/${PR_SOURCE_REPO}/pull/${PR_NUMBER}',^g" docusaurus.config.js
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
          PR_SOURCE_REPO: ${{ github.event.pull_request.head.repo.full_name }}
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'

      - name: Build Website
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  pr_comment:
    name: Post Preview Link (PRs)
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Add PR Comment with Preview Link
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "Preview website is available [here](https://pages.github.com/${{ github.repository }}/@${{ github.head_ref }})."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
